from typing import List, Dict, Any

DEFAULT_ACTIVITIES: List[Dict[str, Any]] = [
    # 2-minute activities
    {
        "title": "2-Minute Box Breathing",
        "category": "relaxation",
        "duration_minutes": 2,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "mindful",
        "required_resources": "none",
        "instructions": "Inhale for 4 seconds, hold for 4 seconds, exhale for 4 seconds, hold for 4 seconds. Repeat 4 times to reset your focus.",
    },
    {
        "title": "Hydrate & Window Gaze",
        "category": "relaxation",
        "duration_minutes": 2,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "mindful",
        "required_resources": "glass of water",
        "instructions": "Pour a tall glass of cold water. Look out the farthest window while drinking slowly.",
    },
    {
        "title": "Desk Shoulder & Neck Reset",
        "category": "exercise",
        "duration_minutes": 2,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "physical",
        "required_resources": "none",
        "instructions": "Gently roll shoulders backward 10 times, stretch neck left and right, release tension built from screen posture.",
    },
    {
        "title": "One-Sentence Journal Micro-Note",
        "category": "creative",
        "duration_minutes": 2,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "creative",
        "required_resources": "notepad or phone notes",
        "instructions": "Write down exactly one interesting observation or thought from your day so far.",
    },
    {
        "title": "Listen to One Pure Instrumental Song",
        "category": "music",
        "duration_minutes": 3,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "relaxing",
        "required_resources": "headphones",
        "instructions": "Put on headphones, close your eyes, and listen to a single acoustic or ambient track without multitasking.",
    },

    # 5-10 minute activities
    {
        "title": "10-Minute Continuous Line Sketch",
        "category": "drawing",
        "duration_minutes": 10,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "creative",
        "required_resources": "pen and paper",
        "instructions": "Pick an object on your desk. Draw it without lifting your pen from the paper for 10 minutes. No erasing.",
    },
    {
        "title": "Solve One Algorithmic Micro-Puzzle",
        "category": "coding",
        "duration_minutes": 10,
        "difficulty": "medium",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "intellectual",
        "required_resources": "laptop or code editor",
        "instructions": "Pick a simple string or array challenge and write a clean, readable 10-line solution.",
    },
    {
        "title": "Brisk Sunlight Outdoor Walk",
        "category": "walking",
        "duration_minutes": 10,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "physical",
        "required_resources": "walking shoes",
        "instructions": "Step outside around the block. Leave notifications muted and observe trees, architecture, or ambient sounds.",
    },
    {
        "title": "Read 5 Pages of Non-Fiction",
        "category": "reading",
        "duration_minutes": 10,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "intellectual",
        "required_resources": "physical book or e-reader",
        "instructions": "Open your current book and read just 5 pages uninterrupted.",
    },
    {
        "title": "Curate a 3-Track Focus Playlist",
        "category": "music",
        "duration_minutes": 10,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "creative",
        "required_resources": "music streaming app",
        "instructions": "Find three songs that evoke deep calm or sharp focus and save them into a new pocket playlist.",
    },
    {
        "title": "Prepare an Artisanal Herbal Tea or Coffee",
        "category": "cooking",
        "duration_minutes": 10,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "relaxing",
        "required_resources": "kettle and mug",
        "instructions": "Make your favorite warm beverage with complete sensory attention to aromas, steam, and warmth.",
    },
    {
        "title": "Send a Warm Check-in Voice Note",
        "category": "socializing",
        "duration_minutes": 5,
        "difficulty": "easy",
        "social_type": "social",
        "energy_level": "low",
        "reward_type": "mindful",
        "required_resources": "phone",
        "instructions": "Send a 60-second voice note to a friend or family member simply asking how their week is progressing.",
    },

    # 15-20 minute activities
    {
        "title": "20-Minute Deep Stretch & Foam Rolling",
        "category": "exercise",
        "duration_minutes": 20,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "low",
        "reward_type": "physical",
        "required_resources": "yoga mat or rug",
        "instructions": "Hold hamstring, hip flexor, and chest opening stretches for 60 seconds each.",
    },
    {
        "title": "Refactor a Small Component or Function",
        "category": "coding",
        "duration_minutes": 20,
        "difficulty": "medium",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "intellectual",
        "required_resources": "development environment",
        "instructions": "Pick an existing pet project and improve readability or type definitions for 20 focused minutes.",
    },
    {
        "title": "Quick Acoustic Jam or Beat Sketch",
        "category": "music",
        "duration_minutes": 20,
        "difficulty": "medium",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "creative",
        "required_resources": "instrument or DAW",
        "instructions": "Play chord progressions or build an 8-bar loop freely without judging the outcome.",
    },
    {
        "title": "Explore a Chapter of an Open Course",
        "category": "learning",
        "duration_minutes": 20,
        "difficulty": "medium",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "intellectual",
        "required_resources": "browser or notebook",
        "instructions": "Study one standalone concept in design, science, or history that you've been curious about.",
    },
    {
        "title": "Cook a Fresh Nutritious Snack",
        "category": "cooking",
        "duration_minutes": 15,
        "difficulty": "easy",
        "social_type": "solo",
        "energy_level": "medium",
        "reward_type": "physical",
        "required_resources": "fresh ingredients",
        "instructions": "Chop fruit, toast nuts, or prepare a fresh bruschetta with care.",
    }
]


def seed_activities_if_empty(db_session):
    """Seed the default activity library if it contains no records"""
    from backend.app.models.activity import Activity
    count = db_session.query(Activity).count()
    if count == 0:
        for act in DEFAULT_ACTIVITIES:
            new_act = Activity(
                title=act["title"],
                category=act["category"],
                duration_minutes=act["duration_minutes"],
                difficulty=act["difficulty"],
                social_type=act["social_type"],
                energy_level=act["energy_level"],
                reward_type=act["reward_type"],
                required_resources=act["required_resources"],
                instructions=act["instructions"],
                is_active=True
            )
            db_session.add(new_act)
        db_session.commit()
